server {
    host 0.0.0.0
    port 8890
    default_server_root www
    timeout 60000

    route /api {
        root www
        default_file index.html
        error_page 404 www/errors/custom_404.html
        error_page 403 www/errors/401.html
    }

    route /files {
        root www
        directory_listing true
    }

    route /docs {
        redirect https://aaa.com/docs
    }

    route /cgi {
        root www/cgi
        default_file index.py
        cgi_extensions .py .sh
    }
}

server {
    host 0.0.0.0
    port 8889
    default_server_root www/admin
    error_page 403 www/errors/401.html
    error_page 404 www/errors/404.html
}
